fix: Requirements for "label-studio-ml init my_backend" command (#226)
* Added rq to run "label-studio-ml init my_backend"

I was getting the follow runtime error because rq is used but not imported:

from rq import Queue, get_current_job
ModuleNotFoundError: No module named 'rq'

* Adding redis and rq

When running "label-studio-ml init my_backend" I was getting a runtime error of:

import redis
ModuleNotFoundError: No module named 'redis'

and

import rq
ModuleNotFoundError: No module named 'rq'

* Update requirements.txt

---------

Co-authored-by: Max Tkachenko <makseq@gmail.com>